pipeline:
  build_docker_image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t openjdk10:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, pull_request]

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_QUAY_PASSWORD}" "${DOCKER_REPO}"
      - docker tag openjdk10:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/openjdk10:$${DRONE_COMMIT_SHA}
      - docker tag openjdk10:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/openjdk10:latest
      - docker push quay.io/ukhomeofficedigital/openjdk10:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/openjdk10:latest
    when:
      event: push
      branch: master

  tagged_image_to_quay:
    image: docker:17.09.1
    secrets: [ docker_password ]
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_QUAY_PASSWORD}" "${DOCKER_REPO}"
      - docker tag openjdk10:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/openjdk10:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/openjdk10:$${DRONE_TAG}
    when:
      event: tag
