pipeline:
  build_docker_image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t openjdk10:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, pull_request]

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - quay_token
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+digperms" -p=$${QUAY_TOKEN} quay.io
      - docker tag openjdk10:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/openjdk10:$${DRONE_COMMIT_SHA}
      - docker tag openjdk10:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/openjdk10:latest
      - docker push quay.io/ukhomeofficedigital/openjdk10:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/openjdk10:latest
    when:
      event: push
      branch: master
