pipeline:
  build_docker_image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t openjdk10:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, pull_request]

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="digperms" -p=$${ARTIFACTORY_TOKEN} docker.digital.homeoffice.gov.uk
      - docker tag openjdk10:$${DRONE_COMMIT_SHA} docker.digital.homeoffice.gov.uk/openjdk10:$${DRONE_COMMIT_SHA}
      - docker tag openjdk10:$${DRONE_COMMIT_SHA} docker.digital.homeoffice.gov.uk/openjdk10:latest
      - docker push docker.digital.homeoffice.gov.uk:$${DRONE_COMMIT_SHA}
      - docker push docker.digital.homeoffice.gov.uk/openjdk10:latest
    when:
      event: push
      branch: master

  tagged_image_to_quay:
    image: docker:17.09.1
    secrets: [ docker_password ]
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="digperms" -p=$${ARTIFACTORY_TOKEN} quay.io
      - docker tag openjdk10:$${DRONE_COMMIT_SHA} docker.digital.homeoffice.gov.uk/openjdk10:$${DRONE_TAG}
      - docker push docker.digital.homeoffice.gov.uk/openjdk10:$${DRONE_TAG}
    when:
      event: tag
